src/FluentSchema.js
src/FluentSchema.test.js

-  `.minimum(0.01)` // BUG Error: 'minimum' must be an Integer
-  `.examples([1000000.00])` BUG Error: 'amount' as 'number' doesn't accept 'examples' option
- `.title('Direct')`  // BUG 'direct' as 'boolean' doesn't accept 'title' option

Fix a few bugs

---

README.md
package.json
src/FluentSchema.integration.test.js
src/FluentSchema.js
src/FluentSchema.test.js
src/utils.js

In the end, it has been easy to support the two syntaxes. The new one is nicer after the code is beautified  👻 
On the other hand, the other one can be better in some use cases so I kept both

Add prop configuration via FluentSchema

---

src/FluentSchema.test.js
src/utils.js

Hi, it looks like that the `date-time` format is missing in the `FORMATS` array, so I have added it since it is [part of the specification](https://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3.1) and it is [supported by Ajv](https://ajv.js.org/#formats).

Add support for date-time format

---

README.md
docs/API.md
src/FluentSchema.integration.test.js
src/FluentSchema.js
src/FluentSchema.test.js
src/example.js
src/utils.js

It works but the implementation is quite fragile. 
```js
const schema = FluentSchema()
.prop('foo', FluentSchema().asString().required())
```
The main issue is that `required` has to be added to the parent schema. 
```json
{
"$schema": "http://json-schema.org/draft-07/schema#",
"type": "object",
"properties": {
"foo": {
"type": "string"
}
},
"required": [
"foo"
]
}
```
So I need to mark a prop as required. Then I remove the required from the prop and I add it to the parent. 
I will think a bit more about how to do in a better way. Feedback welcome

Support required in nested prop (#19)

---

README.md
package.json
src/BaseSchema.test.js
src/FluentSchema.integration.test.js
src/FluentSchema.test.js
src/ObjectSchema.js
src/ObjectSchema.test.js
src/example.js

it's potentially a breaking change because previously this code:
```js
S.object().prop('foo')
```
was generating this schema:
```json
{
"$schema": "http://json-schema.org/draft-07/schema#",
"type": "object",
"properties": {
"foo": {
"type": "string",
}
}
}
```
now it returns this one:
```json
{
"$schema": "http://json-schema.org/draft-07/schema#",
"type": "object",
"properties": {
"foo": {}
}
}
```
which is correct because a prop without a `type` accepts `any`, not a `string`
I will release this as `v0.7.0`

Remove type string as default value when a prop is created

---

README.md
src/ArraySchema.test.js
src/BaseSchema.js
src/BaseSchema.test.js
src/BooleanSchema.test.js
src/IntegerSchema.test.js
src/MixedSchema.js
src/MixedSchema.test.js
src/NullSchema.js
src/NullSchema.test.js
src/NumberSchema.test.js
src/ObjectSchema.test.js
src/StringSchema.test.js
src/utils.js

As titled.
Thanks to this symbol, other libraries that accept validation objects, can directly accept fluent schema objects and call `.valueOf` internally.
This vastly improves the user experience and hides one of the most common mistakes that devs make with this library.
```js
const S = require('fluent-schema')
const schema = S.object()
.prop('foo', S.string())
.prop('bar', S.number())
console.log(schema[Symbol.for('fluent-schema-object')]) // true
```
Once this pr is merged and released, I'll open a pr to Fastify to support this new feature.

Added symbol to identify fluent schema objects

---

README.md
package.json
src/BaseSchema.js
src/BaseSchema.test.js
src/FluentSchema.integration.test.js
src/NullSchema.js
src/utils.js

The issue I was having in #39 was due to object composition and cloning. I have a wrapper around Fastify that reads a list of routes from `config/routes.js` and then the corresponding handlers from `lib/handlers/`. For example:
`config/routes.js`:
```js
module.exports = [{
path: '/foo',
method: 'GET',
handler: 'foo'
}]
```
`lib/handlers/foo.js`:
```js
module.exports = {
schema: {
query: { fluent.object().prop('foo', fluent.string()) }
},
handler(req, res) {
res.send(req.query)
}
}
```
So these two files are read in and the objects are merged to build up the full route definition before being passed to `fastify.route`. If any of the schemas are `fluent-schema` instances then the `Symbol.for('fluent-schema-object')` will be lost during this process because symbols do not get copied in any …

Add boolean to detect object type

---

README.md
src/BaseSchema.js
src/FluentSchema.d.ts
src/FluentSchema.integration.test.js
src/FluentSchema.js
src/ObjectSchema.test.js
src/example.js
src/types/index.ts
src/utils.js

Normally inheritance with JSON Schema is achieved with `allOf`. However when `.additionalProperties(false)` is used the validator won't
understand which properties come from the base schema. `S.extend` creates a schema merging the base into the new one so that the validator knows all the properties because it's evaluating only a single schema.
For example in a CRUD API `POST /users` could use the `userBaseSchema` rather than `GET /users` or `PATCH /users` use the `userSchema` whose contains the `id`, `createdAt` and `updatedAt` generated server side
related to #46

Compose schemas #46

---

README.md
docs/API.md
src/ArraySchema.js

What I've done:
1. Make the link to API documentation more conspicuous.
2. Fix this line (https://github.com/fastify/fluent-schema/blob/7844513d1a47831d26ae822e223d890323194a5e/src/ArraySchema.js#L18) of JSDoc and run `yarn doc`.

Improve docs

---

docs/API.md
src/ArraySchema.js
src/BaseSchema.js
src/FluentSchema.js
src/NullSchema.js
src/NumberSchema.js
src/ObjectSchema.js
src/StringSchema.js

Fix wrong jsdoc links

---

.gitignore
src/ArraySchema.test.js
src/ObjectSchema.js

Allow empty array as default value for a prop.

fix: allow empty array as default value for a prop

---

src/ObjectSchema.js
src/ObjectSchema.test.js
src/utils.js

Better merge strategy. Before, the merge was replacing the array element rather than merging the items. 
I decided to block all the method after `.extend` to avoid incorrect usage. 
Wrong but no error raised by FluentSchema
```
const SCHEMA_BASE = S.object()
.prop(
'reason',
S.string()
.title('Reason 1')
)
const base = S.object()
.extend(SCHEMA_BASE)
.prop(
'reason',
S.string()
.minLength(1)
)
```
Correct usage should be:
```
const extended = S.object()
.prop(
'reason',
S.string()
.minLength(1)
)
.extend(SCHEMA_BASE)
```
First, the schema is defined with all the props then it extends the base schema. 
With the sealed schema after the `.extend` the only thing that can be done is calling `valueOf` 
I'm unsure if I should mark this as 1.0.2 because it's a bug fix or considering the sealing …

Extend schema fixes #65

---

.github/workflows/ci.yaml
.travis.yml
src/ObjectSchema.js
src/ObjectSchema.test.js
src/utils.js

@jmav reported an issue with multiple extends in the #69 PR
I added the fix and the tests to cover that

#69 fix multiple extensions issue

---

src/FluentSchema.d.ts
src/types/index.ts

#80 has updated the ```extend``` API result type, however it lead to the type mismatch in ```ArraySchema.items```, ```Array.Schema.addtionalItems``` API argument.
This PR is used to fix those type mismatch issue.

fix: items, additionItems, propertyNames API type mismatch

---

README.md

Even though this package's name is not prefixed with `fastify-*`, I still initially assumed that it was only intended for use with Fastify. I think it might encourage more widespread usage if the README highlights that this package is framework agnostic.

Highlight that this package is framework agnostic

---

README.md
src/FluentSchema.d.ts
src/ObjectSchema.js
src/ObjectSchema.test.js
src/types/index.ts

Implements my idea @ https://github.com/fastify/fluent-schema/issues/84

Adds 'only' to ObjectSchema to return a subset of properties

---

src/ObjectSchema.js
src/ObjectSchema.test.js

Previously, if an object's properties were restricted with `.only([...])`, props that were removed were still required. (See the test I added for an example that was previously failing.)

Make only() work correctly with required properties

---

src/BaseSchema.test.js
src/FluentSchema.integration.test.js
src/RawSchema.test.js
src/utils.test.js

Main purpose of this commit is to fix `expect` statements being outside of `it` blocks.
`expects` aren't executed outside of `it` or `test` blocks.

Fix test assertions

---

src/FluentJSONSchema.d.ts
src/types/index.ts

Fix `ObjectSchema` cannot extend `ExtendedSchema` in TypeScript
Resolve: #108 

fix: object schema extend extended schema

---

src/BaseSchema.js
src/BaseSchema.test.js
src/utils.js

Fixes #114 by checking values on `required` array.

fix: ensure required() calls generates a valid required array with unique values

---

src/BaseSchema.js
src/BaseSchema.test.js
src/FluentJSONSchema.d.ts
src/MixedSchema.js
src/ObjectSchema.js
src/types/index.ts
src/utils.js

Adding support to `deprecated` values.
[Reference](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.3):
```
The value of this keyword MUST be a boolean. When multiple occurrences of this keyword are applicable to a single sub-instance, applications SHOULD consider the instance location to be deprecated if any occurrence specifies a true value.
If "deprecated" has a value of boolean true, it indicates that applications SHOULD refrain from usage of the declared property. It MAY mean the property is going to be removed in the future.
A root schema containing "deprecated" with a value of true indicates that the entire resource being described MAY be removed in the future.
When the "deprecated" keyword is applied to an item in an array by means of "items", if …
```

adding deprecated function to BaseSchema

---

.husky/pre-commit
.npmignore
package.json

Husky hooks were moved from `package.json` and `.huskyrc.json` to `.husky` directory in Husky v6.
See https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v8

chore: fix husky git hooks

---

types/FluentJSONSchema.d.ts
types/FluentJSONSchema.test-d.ts

Add some utilities for better typing in ObjectSchema.

feat: add improvements in Typescript API

---

src/ArraySchema.test.js
src/BaseSchema.test.js
src/BooleanSchema.test.js
src/FluentSchema.integration.test.js
src/IntegerSchema.test.js
src/MixedSchema.test.js
src/NullSchema.test.js
src/NumberSchema.test.js
src/ObjectSchema.test.js
src/RawSchema.test.js
src/StringSchema.test.js

This PR:
- replaces use of `toEqual()` with `toBe()` or `toBeNull()` when expecting primitive literals, as [recommended in Jest documentation](https://jestjs.io/docs/expect#tobevalue)
- replaces `toThrowError()` with its canonical name `toThrow()` as the aliased method is going to be removed in the next major version of Jest, see https://github.com/facebook/jest/issues/13164

test: tidy test syntax

---

.github/workflows/ci.yml

See https://github.com/fastify/workflows/pull/80, removed from all shared workflows due to issues.

ci(ci): exclude node 14 on windows

---

types/FluentJSONSchema.d.ts

Including this library into a Platformatic project led to a compile error reported [here](https://github.com/fastify/help/issues/933)
I see there was a duplicate interface declaration for `SchemaOptions` one exported, one local.
I think it was a mistake so I removed. the local one. With this fix TypeScript compiler is happy.

fix(types): Removes duplicate interface SchemaOptions declaration

---

types/FluentJSONSchema.d.ts
types/FluentJSONSchema.test-d.ts

Since type `MixedSchema` seemed that it should be implemented simpler, this PR implements that.
This PR also enables typeof S.mixed to be `<T extends TYPE[]>(types: T) => MixedSchema<T>`.

fix: simplify mixed schema
