fastify/fluent-json-schema

- README.md
- docs/API.md
- package.json
- src/FluentSchema.integration.test.js
- src/FluentSchema.js
- src/FluentSchema.test.js
- src/example.js
- src/utils.js
- yarn.lock
- adding JSDoc (WIP)
- add options to FluentSchema function
- Implemented generateIds (default is false) 
TODO
> Add options and JSDoc

- src/FluentSchema.d.ts
- src/FluentSchema.js
- src/FluentSchema.test.js
- src/types/index.ts
it's related to issue #12. 
Extra I added a quick fix to support RegEx
> Support not json data

- docs/API.md
- src/FluentSchema.integration.test.js
- src/FluentSchema.js
- src/FluentSchema.test.js
> Fix anyOf, allOf, oneOf implementation (issue #18)

- .travis.yml
- src/BaseSchema.js
- src/BaseSchema.test.js
> Fix for nested props after required is used #31

- src/BaseSchema.test.js
- src/FluentSchema.d.ts
- src/types/index.ts
- src/utils.js
- Fix null TS definition 
- Fix null detection in isFluentSchema
> Fix TS type definition for NullSchema

- src/FluentSchema.d.ts
- src/types/index.ts
- Fix ifThen ifThenElse and required types #34
- Accept native regex in pattern #35
> Fixes a couple of Typescript bugs

- package.json
- src/BaseSchema.js
- src/BaseSchema.test.js
- src/FluentSchema.d.ts
- src/types/index.ts
I saw that these two attributes exist here: https://json-schema.org/latest/json-schema-validation.html#rfc.section.10.3
> add readOnly and writeOnly

- src/FluentSchema.d.ts
- src/types/index.ts
Added `isFluentSchema` in the TS definitions
> Export isFluentSchema prop in the typescript definitions

- src/ObjectSchema.js
- src/ObjectSchema.test.js
As for discussion on #41 I added additionalProperties(true) as valid use case
> Fix: additionalProperties can handle true as value #41

- src/BaseSchema.js
- src/BaseSchema.test.js
> #50 use options.factory in ifThen and ifThenElse

- src/ArraySchema.js
- src/ArraySchema.test.js
- src/BaseSchema.js
- src/BaseSchema.test.js
- src/FluentSchema.d.ts
- src/FluentSchema.js
- src/IntegerSchema.test.js
- src/MixedSchema.test.js
- src/NumberSchema.js
- src/NumberSchema.test.js
- src/ObjectSchema.js
- src/ObjectSchema.test.js
- src/RawSchema.js
- src/RawSchema.test.js
- src/StringSchema.js
- src/StringSchema.test.js
- src/types/index.ts
- src/utils.js
related to #61 
- Better error messages 
- Added FluentSchemaError
> Fix prop type checking

- src/FluentSchema.d.ts
- src/types/index.ts
The TS types did not describe the FORMATS object exported as a prop on `S`. This resolves that.
> added types for FORMATS

- src/ObjectSchema.js
- src/ObjectSchema.test.js
Related to #75 
it allows multiple extend
> #75 allow extend

- README.md
Add missing link for AJV and point to the project homepage.
> docs: Fix ajv link in README

- .github/workflows/ci.yaml
- README.md
- package.json
- src/BaseSchema.js
- src/FluentSchema.integration.test.js
- src/types/index.ts
Drop fluent-schema-refs 
related #87
> Fix some missing references to Fluent JSON schema

- .github/workflows/ci.yml
- README.md
- package.json
This merge request adds test coverage generation to the CI GitHub Actions workflow and closes #28
> Fix test coverage

- package.json
Forgot to remove this after using it in #100 for testing, sorry!
It isn't needed as the GitHub Action is already pushing coverage data to Coveralls.
Should reduce resulting package-lock.json by a bit: https://bundlephobia.com/result?p=coveralls@3.1.0
> build(deps-dev): remove coveralls

- .gitignore
> chore(gitignore): add editor/ide files

- .github/workflows/ci.yml
> ci: add node 18 to test matrix

- src/BooleanSchema.js
- src/MixedSchema.js
- src/ObjectSchema.js
Remove unused imports and variables to fix lgtm alerts
https://lgtm.com/projects/g/fastify/fluent-json-schema/?mode=tree&ruleFocus=1780092
> remove unused imports and variables, fix lgtm alerts

- README.md
See https://github.com/fastify/fastify/pull/3875
> docs: use `npm install` alias; remove redundant `--save` arg

- README.md
> Replace Prettier badge with StandardJS

- src/ArraySchema.test.js
- src/BaseSchema.test.js
- src/BooleanSchema.test.js
- src/FluentSchema.integration.test.js
- src/FluentSchema.test.js
- src/IntegerSchema.test.js
- src/MixedSchema.test.js
- src/NullSchema.test.js
- src/NumberSchema.test.js
- src/ObjectSchema.test.js
- src/RawSchema.test.js
- src/StringSchema.test.js
- src/utils.test.js
> test: add missing `use strict` directives

- src/utils.js
See https://github.com/fastify/fastify-helmet/issues/236
> refactor(utils): replace `typeof` undefined check
